# Generated by Django 5.1.2 on 2024-10-21 23:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_post_reposted_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='unliked_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
