# Generated by Django 5.1.2 on 2024-10-26 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_post_reposted_from_repost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reposted_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reposts', to='api.post'),
        ),
        migrations.DeleteModel(
            name='Repost',
        ),
    ]
