# Generated by Django 5.1.2 on 2024-10-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_post_reposted_from_delete_repost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='reposted_from',
            new_name='original_post',
        ),
        migrations.AddField(
            model_name='post',
            name='is_repost',
            field=models.BooleanField(default=False),
        ),
    ]
