# Generated by Django 5.1.2 on 2024-10-27 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_reposted_from_post_original_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='original_post',
            new_name='reposted_from',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_repost',
        ),
    ]
