# Generated by Django 5.1.2 on 2024-10-30 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_original_post_post_reposted_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reposted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reposted_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
